[package]
name = "amplify"
version = "2.3.0"
description = "Amplifying Rust language capabilities: multiple generic trait implementations, type wrappers, derive macros"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>", "Martin Habovstiak <martin.habovstiak@gmail.com>"]
keywords = ["generics", "core", "no_std", "wrap", "patterns"]
categories = ["data-structures", "no-std", "rust-patterns"]
repository = "https://github.com/LNP-BP/rust-amplify"
homepage = "https://github.com/LNP-BP"
license = "MIT"
readme = "README.md"
edition = "2018"
exclude = [".github", "derive", "serde_str_helpers", "stringly_conversions"]

[dependencies]
amplify_derive = "~2.2.1"
torut = { version = "~0.1.6", features = ["v2", "v3"], optional = true }
ed25519-dalek = { version = "~1.0.0", optional = true }
parse_arg = { version = "~0.1.4", optional = true }
# This strange naming is a workaround for not being able to define required features for a dependency
# See https://github.com/rust-lang/api-guidelines/issues/180 for the explanation and references.
serde_crate = { package = "serde", version = "~1.0.111", features = ["derive"], optional = true }
serde_json = { version = "~1.0.55", optional = true }
serde_yaml = { version = "~0.8.13", optional = true }
toml = { version = "~0.5.6", optional = true }
stringly_conversions = { version = "~0.1.1", optional = true, features = ["alloc"] }

[lib]
name = "amplify"
path = "src/lib.rs"

[features]
all = ["serde", "std", "tor", "parse_arg", "stringly_conversions"]
serde = ["serde_crate", "torut/serialize", "std",
         "serde_yaml", "serde_json", "toml",
         "stringly_conversions",
         "stringly_conversions/alloc",
         "stringly_conversions/serde_str_helpers"]
default = ["std"]
std = []
tor = ["torut/v3", "torut/v2", "ed25519-dalek", "parse_arg", "std"]
vendored_openssl = ["torut/vendored_openssl"]

[workspace]
members = [".", "derive", "serde_str_helpers", "stringly_conversions"]
default-members = ["."]
