[package]
name = "amplify"
version = "1.0.0"
description = "Amplifying Rust language capabilities: multiple generic trait implementations, type wrappers, derive macros"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>", "Martin Habovstiak <martin.habovstiak@gmail.com>"]
keywords = ["generics", "core", "no_std", "wrap", "patterns"]
categories = ["data-structures", "no-std", "rust-patterns"]
repository = "https://github.com/LNP-BP/rust-amplify"
homepage = "https://github.com/LNP-BP"
license = "MIT"
readme = "README.md"
edition = "2018"

[dependencies]
serde = { version = "~1.0.111", features = ["derive"], optional = true }

[lib]
name = "amplify"
path = "src/lib.rs"

[features]
all = ["serde", "std"]
default = ["std"]
std = []

[workspace]
members = ["derive", "."]
default-members = ["derive", "."]
