[package]
name = "amplify"
version = "0.1.1"
description = "Amplifying Rust language capabilities: multiple generic trait implementations, type wrappers, derive macros"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>", "Martin Habovstiak <martin.habovstiak@gmail.com>"]
keywords = ["generics", "core", "no_std", "wrap", "patterns"]
categories = ["data-structures", "no-std", "rust-patterns"]
repository = "https://github.com/LNP-BP/rust-amplify"
homepage = "https://github.com/LNP-BP"
license-file = "LICENSE"
license = "MIT"
readme = "README.md"
edition = "2018"

[dependencies]
serde_derive = { version = "~1.0.111", optional = true }

[lib]
name = "amplify"
path = "src/lib.rs"

[features]
default = ["std"]
std = []

[badges]
travis-ci = { repository = "LNP-BP/rust-amplify" }
