[package]
name = "amplify"
version = "1.1.0"
description = "Amplifying Rust language capabilities: multiple generic trait implementations, type wrappers, derive macros"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>", "Martin Habovstiak <martin.habovstiak@gmail.com>"]
keywords = ["generics", "core", "no_std", "wrap", "patterns"]
categories = ["data-structures", "no-std", "rust-patterns"]
repository = "https://github.com/LNP-BP/rust-amplify"
homepage = "https://github.com/LNP-BP"
license = "MIT"
readme = "README.md"
edition = "2018"

[dependencies]
torut = { version = "~0.1.2", features = ["v2", "v3"], optional = true }
ed25519-dalek = { version = "~1.0.0", optional = true }
async-trait = { version = "~0.1.30", optional = true }
# This strange naming is a workaround for not being able to define required features for a dependency
# See https://github.com/rust-lang/api-guidelines/issues/180 for the explanation and references.
serde_crate = { package = "serde", version = "~1.0.111", features = ["derive"], optional = true }

[lib]
name = "amplify"
path = "src/lib.rs"

[features]
all = ["serde", "std", "tor", "async"]
serde = ["serde_crate", "torut/serialize", "std"]
default = ["std"]
std = []
tor = ["torut/v3", "torut/v2", "ed25519-dalek"]
async = ["async-trait", "std"]

[workspace]
members = ["derive", "."]
default-members = ["derive", "."]
